// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HordeWebSite.Data;

namespace HordeWebSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210612184046_changeImageNameDown")]
    partial class changeImageNameDown
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("training1.Models.Down", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member8")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Down");
                });

            modelBuilder.Entity("training1.Models.Gazette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("image")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("page")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gazettes");
                });
#pragma warning restore 612, 618
        }
    }
}
